version: "3.9"

services:
  frontend:
    build: ./app/frontend
    ports:
      - 3030:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3030"]  # Caso utilize outra porta interna para o front, altere ela aqui também
      timeout: 10s
      retries: 5
  backend:
    build: ./app/backend
    ports:
      - 3031:3031
    platform: linux/x86_64
    working_dir: /app-backend
    environment:
      - PORT=3031
      - JWT_SECRET=jwt_secret
      - DB_PORT=27017
      - DB_HOST=database
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3031"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5
    depends_on:
      - "database"
  database:
    image: mongo:5
    platform: linux/x86_64
    ports:
      - 27017:27017
    restart: 'always'
    cap_add:
      - SYS_NICE # Deve omitir alertas menores